// order
export const RECEIVE_ORDER_RECORDS = 'RECEIVE_ORDER_RECORDS';
export const RECEIVE_ORDER_RECORDS_ERROR = 'RECEIVE_ORDER_RECORDS_ERROR';
export const RECEIVE_ORDER_CATEGORIES = 'RECEIVE_ORDER_CATEGORIES';
export const RECEIVE_ORDER_CATEGORIES_ERROR = 'RECEIVE_ORDER_CATEGORIES_ERROR';
