// order
export const RECEIVE_ORDER_RECORDS = 'RECEIVE_ORDER_RECORDS';
export const RECEIVE_ORDER_RECORDS_ERROR = 'RECEIVE_ORDER_RECORDS_ERROR';
export const RECEIVE_ORDER_CATEGORIES = 'RECEIVE_ORDER_CATEGORIES';
export const RECEIVE_ORDER_CATEGORIES_ERROR = 'RECEIVE_ORDER_CATEGORIES_ERROR';
export const RECEIVE_ORDER_STATISTICS = 'RECEIVE_ORDER_STATISTICS';
export const RECEIVE_ORDER_STATISTICS_ERROR = 'RECEIVE_ORDER_STATISTICS_ERROR';

// user
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const RECEIVE_USER_INFO_ERROR = 'RECEIVE_USER_INFO_ERROR';
