openapi: "3.0.2"

info:
  title: Order Manage
  description: "訂單 API，路徑需為: /order_api"
  version: "0.1.0"
servers:
- url: "http://localhost"
  description: local

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    UserTokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          examples:
            API-Key-Error:
              value:
                message: "API key is missing or invalid"
            Token-Error:
              value:
                message: "Authorization token is missing or invalid"
    BadRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                properties:
                  message:
                    type: string
                    example: "error bad request"

              - type: object
                properties:
                  message:
                    type: string
                    example: "error bad request"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        domain:
                          type: string
                          example: "abc.com"
                        result:
                          type: string
                          example: "can not use"
  parameters:
    PageParam:
      in: query
      name: page
      schema:
        type: integer
      example: 1
    PerPageParam:
      in: query
      name: per_page
      schema:
        type: integer
      example: 20

paths:
  /order_api/orders/{year}/record:
    get:
      tags:
        - 訂單記錄
      summary: 指定年份的訂單記錄清單
      description: 指定年份的訂單記錄清單
      parameters:
        - name: year
          required: true
          in: path
          schema:
            type: integer
            example: 2022
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string                      
                    sex:
                      type: string
                    order_items:
                      type: array
                      items:
                        type: string
                    order_date:
                      type: string
                      format: date-time
                    payment_status:
                      type: integer
                    note:
                      type: string                      
              example:
                  - id: 1
                    name: "王力紅"
                    sex: "male"
                    order_items: ["體重計"]
                    order_date: "2022-01-05T08:30:00Z"
                    payment_status: 1
                    note: "備註 1"
                  - id: 2
                    name: "周截倫"
                    sex: "male"
                    order_items: ["智慧手錶", "體重計"]
                    order_date: "2022-01-03T08:30:00Z"
                    payment_status: 2
                    note: "備註 2"
                  - id: 3
                    name: "賽琳娜紅"
                    sex: "female"
                    order_items: ["雕塑營課程", "智慧手錶"]
                    order_date: "2022-01-03T08:30:00Z"
                    payment_status: 1
                    note: ""
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
           description: Internal error

  /order_api/orders/{year}/categories:
    get:
      tags:
        - 訂單記錄
      summary: 指定年份的訂單分類數據
      description: 指定年份的訂單分類數據
      parameters:
        - name: year
          required: true
          in: path
          schema:
            type: integer
            example: 2022
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    value:
                      type: number                      
              example:
                  - type: "線上課程"
                    value: 27
                  - type: "穿戴裝置"
                    value: 18
                  - type: "健身保健/代餐"
                    value: 15
                  - type: "運動配件/服飾"
                    value: 10
                  - type: "其他"
                    value: 10                    
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
           description: Internal error
           
  /order_api/orders/{year}/statistics:
    get:
      tags:
        - 訂單記錄
      summary: 指定年份的訂單資料統計
      description: 指定年份的訂單資料統計
      parameters:
        - name: year
          required: true
          in: path
          schema:
            type: integer
            example: 2022
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  renew_amount:
                    type: integer
                    example: 999
                  renew_percent:
                    type: number
                    format: float
                    example: 50.02
                  monthly_revenue:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        value:
                          type: number
                    example:
                      - type: "1月"
                        value: 246666
                      - type: "2月"
                        value: 12345
                      - type: "3月"
                        value: 123456
                      - type: "4月"
                        value: 100000
                      - type: "5月"
                        value: 100000
                      - type: "6月"
                        value: 200000
                      - type: "7月"
                        value: 246666
                      - type: "8月"
                        value: 300000
                      - type: "9月"
                        value: 400000
                      - type: "10月"
                        value: 500000
                      - type: "11月"
                        value: 246666
                      - type: "12月"
                        value: 246666                        
                  
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
           description: Internal error          

  /order_api/orders/{order_id}/note:
    patch:
      tags:
        - 訂單備註
      summary: 修改訂單備註
      parameters:
        - name: order_id
          required: true
          in: path
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  type: string
                  example: "修改備註內容"
      responses:
        "204":
          description: No Content
        "400":
          $ref: "#/components/responses/BadRequestError"
        "500":
          description: Internal error
